# Generated by Django 2.2.3 on 2019-07-25 20:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1)),
                ('name_fam', models.CharField(max_length=50)),
                ('years_old', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('inv_number', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='workapp.Worker')),
            ],
        ),
    ]
